Fine-tuning last commit to changes in mono 5.x in System.Security
Tested with:
------------

Group 1:
-------
TERM=xterm MONO_PATH=~/.mono/targets/mono-5.8.0-ubuntu-16.04-x86/lib/mono/4.5/ ~/.mono/targets/mono-5.8.0-ubuntu-16.04-x86/bin/mono  /tmp/Font-Validator/bin/DSIGInfo.exe /tmp/UrdType.ttf
TERM=xterm MONO_PATH=~/.mono/targets/mono-5.10.0-ubuntu-16.04-x86/lib/mono/4.5/ ~/.mono/targets/mono-5.10.0-ubuntu-16.04-x86/bin/mono  /tmp/Font-Validator/bin/DSIGInfo.exe /tmp/UrdType.ttf

https://github.com/mono/mono/issues/11557
System.Exception: Magic number is wrong: 542 #11557 - GitHub
https://github.com/mono/mono/pull/6960
[TermInfo] support new file format terminfo2 introduced with ncurses6.1 #6960
https://bugzilla.redhat.com/show_bug.cgi?id=1659050
Bug 1659050 - System.Exception: Magic number is wrong: 542

Group 2:
-------
MONO_PATH=~/.mono/targets/mono-5.12.0-ubuntu-18.04-x86/lib/mono/4.5/ ~/.mono/targets/mono-5.12.0-ubuntu-18.04-x86/bin/mono  /tmp/Font-Validator/bin/DSIGInfo.exe /tmp/UrdType.ttf

MONO_PATH=~/.mono/targets/mono-5.14.0-ubuntu-16.04-x64/lib/mono/4.5/ ~/.mono/targets/mono-5.14.0-ubuntu-16.04-x64/bin/mono  /tmp/Font-Validator/bin/DSIGInfo.exe /tmp/UrdType.ttf

MONO_PATH=~/.mono/targets/mono-5.16.0-ubuntu-18.04-x86/lib/mono/4.5/ ~/.mono/targets/mono-5.16.0-ubuntu-18.04-x86/bin/mono  /tmp/Font-Validator/bin/DSIGInfo.exe /tmp/UrdType.ttf
MONO_PATH=~/.mono/targets/mono-5.16.1-ubuntu-18.04-x86/lib/mono/4.5/ ~/.mono/targets/mono-5.16.1-ubuntu-18.04-x86/bin/mono  /tmp/Font-Validator/bin/DSIGInfo.exe /tmp/UrdType.ttf

Broken.

Group 3:
-------
MONO_PATH=~/.mono/targets/mono-5.18.0-ubuntu-18.04-x86/lib/mono/4.5/ ~/.mono/targets/mono-5.18.0-ubuntu-18.04-x86/bin/mono  /tmp/Font-Validator/bin/DSIGInfo.exe /tmp/UrdType.ttf

MONO_PATH=~/.mono/targets/mono-5.20.1-ubuntu-18.04-x64/lib/mono/4.5/ ~/.mono/targets/mono-5.20.1-ubuntu-18.04-x64/bin/mono  /tmp/Font-Validator/bin/DSIGInfo.exe /tmp/UrdType.ttf
okay with current code

Okay.

Conclusion:
-----------
Behavior changed between:
5.16.1.0 (tarball Fri Mar 15 15:35:00 UTC 2019)
5.18.0.225 (tarball Fri Dec 21 19:35:56 UTC 2018)